# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55cdca5f25441b1ac2c9d42acc89cf84c2ea4a9904441b7813688ce3e39668b84f4a4bf0c0307e7edb46a77ef6a59b324124054130b1203b15d871e7c5a32d6f

test:
  secret_key_base: 1d12eeb2cc8ecedc2707849704aa01118db7be1d0e98a9589f1c124d9d5cb57ed97ec74e9009ab0eafe71171c1292e7e540c976845b80a54c5a9dd4101bb5ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
